# Generated by Django 5.0.1 on 2024-01-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='description',
            new_name='threads',
        ),
        migrations.RemoveField(
            model_name='finch',
            name='age',
        ),
        migrations.AddField(
            model_name='finch',
            name='habitat',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
